### ISSUE TITLE
俄语的安装页面

### ISSUE THREAD

**Issue by heyxiaobai** [techysy/B450M-MORTAR-Hackintosh#5]
在首次安装页面默认是俄语，且无法修改，建议在config.plist中修改`NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> prev-lang:kbd`

**Comment by techysy** [comment]
我自己安装的时候就是中文，具体的我也不清楚 可能是我下的中文的系统吧 我是在mbp用终端做好的系统。

**Comment by heyxiaobai** [comment]
应该与下载的系统无关，在OC的配置里指定了是俄语（_也许你那边没有清空nvram_），所以建议将上面的值改为 **中文** 或者 **英文**

**Comment by techysy** [comment]
是的这个是在官方论坛，搬运的配置 那个好像是毛子发的~

**Comment by techysy** [comment]
留白就是 默认英文 我的可能就是木有重置naram ，我换系统 终端打印看看
